{

	"user": [
				
		{
			"action": "authentication", 
			"provider": "google",
			"number": 11030, 
			"message": "Authenticated Google user is not a natural person (business or organization)."
		},

		{
			"action": "authentication", 
			"provider": "google",
			"number": 11031, 
			"message": "Authenticated Google user has no public ID or default Google Identifier."
		},

		{
			"action": "authentication", 
			"provider": "google",
			"number": 11032, 
			"message": "No valid user name could be constructed for authenticated Google user."
		},

		{
			"action": "authentication", 
			"provider": "google",
			"number": 11033, 
			"message": "'No email account could be extracted from authenticated Google user's profile."
		},

		{
			"action": "authentication", 
			"provider": "google",
			"number": 11034, 
			"message": "Authenticated Google user has no public ID or default Google Identifier."
		},

		{
			"action": "query_user", 
			"provider": "User Operations",
			"number": 11100, 
			"message": "Error occured while querying user collections for user."
		},

		{
			"action": "test_user_email", 
			"provider": "User Operations",
			"number": 11101, 
			"message": "User has an invalid email address."
		},

		{
			"action": "test_user_password", 
			"provider": "User Operations",
			"number": 11102, 
			"message": "User has entered an invalid password."
		},

		{
			"action": "add_user_authentication_moment", 
			"provider": "User Operations",
			"number": 11110, 
			"message": "Could not generate authentication object aftert user logged on"
		},

		{
			"action": "test_user_firstname", 
			"provider": "User Operations",
			"number": 11120, 
			"message": "New user has entered an invalid first name."
		},

		{
			"action": "test_user_lastname", 
			"provider": "User Operations",
			"number": 11121, 
			"message": "New user has entered an invalid last name."
		},

		{
			"action": "decrypt_user_password", 
			"provider": "User Operations",
			"number": 11130, 
			"message": "Decryption attempt of user password with Crypto and initialization vector failed."
		},

		{
			"action": "decrypt_user_password", 
			"provider": "User Operations",
			"number": 11131, 
			"message": "Decryption attempt of user password with default Crypto failed."
		},

		{
			"action": "decrypt_user_password", 
			"provider": "User Operations",
			"number": 11132, 
			"message": "Decryption attempt of user password with BCrypt failed."
		},

		{
			"action": "encrypt_user_password", 
			"provider": "User Operations",
			"number": 11135, 
			"message": "Encryption attempt of user password with Crypto and initialization vector failed."
		},

		{
			"action": "encrypt_user_password", 
			"provider": "User Operations",
			"number": 11136, 
			"message": "Encryption attempt of user password with default Crypto failed."
		},

		{
			"action": "encrypt_user_password", 
			"provider": "User Operations",
			"number": 11137, 
			"message": "Encryption attempt of user password with BCrypt failed."
		},


		{
			"action": "create_user_directory", 
			"provider": "User Operations",
			"number": 11150, 
			"message": "Creation of public directory for default user failed."
		},

		{
			"action": "create_user_directory", 
			"provider": "User Operations",
			"number": 11151, 
			"message": "Creation of public directory for customer user type failed."
		},

		{
			"action": "find_user", 
			"provider": "User Operations",
			"number": 11160, 
			"message": "An error occured when trying to find local user."
		},

		{
			"action": "insert_user", 
			"provider": "User Operations",
			"number": 11170, 
			"message": "An error occured when trying to insert a new user into the <local> database."
		},

		{
			"action": "insert_user", 
			"provider": "User Operations",
			"number": 11171, 
			"message": "An error occured when trying to insert a new user into the <remote> database."
		},

		{
			"action": "update_user", 
			"provider": "User Operations",
			"number": 11180, 
			"message": "An error occured when trying to update existing user in <local> database."
		},

		{
			"action": "update_user", 
			"provider": "User Operations",
			"number": 11181, 
			"message": "An error occured when trying to update existing user in <remote> database."
		}	],

	"database": [
		{
			"action": "save", 
			"number": 11030, 
			"message": "An error occured when saving new user"
		}

	]
				
}